### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by 9swampy** [dgrubelic/vue-authenticate#119]
What base system should the example work on? I've tried on a windows box as well as a vagranted trusty64 with bare minimum install; node 8.11.1, npm 5.6.0 but both error:
```
vagrant@vagrant-ubuntu-trusty-64:~/vue-authenticate$ npm run dev

> vue-authenticate@1.3.5-beta.1 dev /home/vagrant/vue-authenticate
> parallelshell "node-dev ./example/server.js" "gulp dev"

child_process.js:403
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:403:11)
    at exports.spawn (child_process.js:496:38)
    at /home/vagrant/vue-authenticate/node_modules/parallelshell/index.js:104:17

    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/vagrant/vue-authenticate/node_modules/parallels
hell/index.js:100:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-authenticate@1.3.5-beta.1 dev: `parallelshell "node-dev ./example/s
erver.js" "gulp dev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-authenticate@1.3.5-beta.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-04-05T00_11_02_945Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-authenticate@1.3.5-beta.1~predev: vue-authenticate@1.3.5-b$
6 info lifecycle vue-authenticate@1.3.5-beta.1~dev: vue-authenticate@1.3.5-beta$
7 verbose lifecycle vue-authenticate@1.3.5-beta.1~dev: unsafe-perm in lifecycle$
8 verbose lifecycle vue-authenticate@1.3.5-beta.1~dev: PATH: /home/vagrant/.nvm$
9 verbose lifecycle vue-authenticate@1.3.5-beta.1~dev: CWD: /home/vagrant/vue-a$
10 silly lifecycle vue-authenticate@1.3.5-beta.1~dev: Args: [ '-c',
10 silly lifecycle   'parallelshell "node-dev ./example/server.js" "gulp dev"' ]
11 silly lifecycle vue-authenticate@1.3.5-beta.1~dev: Returned: code: 1  signal$
12 info lifecycle vue-authenticate@1.3.5-beta.1~dev: Failed to exec dev script
13 verbose stack Error: vue-authenticate@1.3.5-beta.1 dev: `parallelshell "node$
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/n$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/n$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pro$
14 verbose pkgid vue-authenticate@1.3.5-beta.1
15 verbose cwd /home/vagrant/vue-authenticate
16 verbose Linux 3.13.0-144-generic
17 verbose argv "/home/vagrant/.nvm/versions/node/v8.11.1/bin/node" "/home/vagr$
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-authenticate@1.3.5-beta.1 dev: `parallelshell "node-dev ./example/$
22 error Exit status 1
23 error Failed at the vue-authenticate@1.3.5-beta.1 dev script.
23 error This is probably not a problem with npm. There is likely additional lo$
24 verbose exit [ 1, true ]
```

FWIW vue-authenticate-site builds but just brings up a blank page.

**Comment by bviala** [comment]
Same problem here

**Comment by 9swampy** [comment]
@bviala glad I'm not silly enough to be the only one! If you get a working example it'd be great if you could post back here please. JS is still a pretty new string in my bow so I'd be very happy to learn! FWIW I found https://github.com/indexzero/daemon.node/issues/41 (not directly related) which suggested maybe node 8 could be the problem so I tried with node 7.10.1 but no joy there. Different error though:
```
vagrant@vagrant-ubuntu-trusty-64:~/vue-authenticate$ npm run dev

> vue-authenticate@1.3.5-beta.1 dev /home/vagrant/vue-authenticate
> parallelshell "node-dev ./example/server.js" "gulp dev"

sh: 1: parallelshell: not found

npm ERR! Linux 3.13.0-144-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v7.10.1/bin/node" "/home/vagrant/.nvm/versions/node/v7.10.1/bin/npm" "run" "dev"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vue-authenticate@1.3.5-beta.1 dev: `parallelshell "node-dev ./example/server.js" "gulp dev"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the vue-authenticate@1.3.5-beta.1 dev script 'parallelshell "node-dev ./example/server.js" "gulp dev"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-authenticate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parallelshell "node-dev ./example/server.js" "gulp dev"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-authenticate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-authenticate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.npm/_logs/2018-04-13T19_35_28_575Z-debug.log
```

FWIW vue-authenticate-site didn't even build with 7.10.1; it "Cannot find module 'chalk'"

**Comment by SET001** [comment]
you can run example using `gulp server` command

**Comment by kururu002** [comment]
Yup, as @SET001 said, what I have done:
- `npm install`
- `gulp server`



NOTE: If you got the following error 

```
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
```

run `npm install natives@1.1.6` as described [here](https://github.com/gulpjs/gulp/issues/2246)
